import { IconType } from "react-icons";
import {
  FiFileText,
  FiImage,
  FiMinimize2,
  FiLayers,
  FiRepeat,
  FiScissors,
  FiEdit,
  FiLock,
  FiArchive,
  FiMaximize2,
  FiFile,
  FiGrid,
  FiRefreshCw,
  FiCode,
} from "react-icons/fi";
import {
  FaFilePdf,
  FaFileWord,
  FaFileImage,
  FaCompress,
  FaObjectGroup,
  FaCut,
  FaEdit,
  FaExchangeAlt,
  FaFileArchive,
  FaFileCsv,
  FaFileExcel,
  FaMagic,
  FaUndo,
  FaSignature,
  FaBalanceScale,
  FaListOl,
} from "react-icons/fa";

export type OutputFormat = "image" | "pdf" | "docx" | "csv" | "excel" | "zip" | "file";

export interface ToolMeta {
  id: string;
  name: string;
  route: string;
  icon: IconType;
  category: "pdf" | "image" | "converter" | "file" | "spreadsheet" | "encoder" | "decoder" | "binary";
  acceptedTypes: string[]; // Input types accepted e.g. ['image/jpeg', 'image/*'], ['application/pdf']
  outputType: OutputFormat; // Primary output file format generated by tool
  maxFiles?: number;
  subtext?: string;
  badge?: string;
}

export const TOOLS_REGISTRY: Record<string, ToolMeta> = {
  // ── PDF Tools ──────────────────────────────────────────────────────
  "pdf-to-jpg": {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    route: "/converter/PDFtools/PdftoJpg",
    icon: FiImage,
    category: "pdf",
    acceptedTypes: ["application/pdf", ".pdf"],
    outputType: "image",
    maxFiles: 1,
    subtext: "Convert document pages to high-quality JPG images",
  },
  "pdf-to-word": {
    id: "pdf-to-word",
    name: "PDF to Word",
    route: "/converter/PDFtools/PDFtoWord",
    icon: FaFileWord,
    category: "pdf",
    acceptedTypes: ["application/pdf", ".pdf"],
    outputType: "docx",
    maxFiles: 1,
    subtext: "Convert PDF documents to editable DOCX format",
  },
  "pdf-merge": {
    id: "pdf-merge",
    name: "PDF Merge",
    route: "/converter/PDFtools/Pdfmerge",
    icon: FaObjectGroup,
    category: "pdf",
    acceptedTypes: ["application/pdf", ".pdf"],
    outputType: "pdf",
    maxFiles: 50,
    subtext: "Combine multiple PDF files into one document",
  },
  "pdf-split": {
    id: "pdf-split",
    name: "PDF Split",
    route: "/converter/PDFtools/Pdfsplit",
    icon: FaCut,
    category: "pdf",
    acceptedTypes: ["application/pdf", ".pdf"],
    outputType: "pdf",
    maxFiles: 1,
    subtext: "Separate pages from your PDF file",
  },
  "pdf-watermark": {
    id: "pdf-watermark",
    name: "PDF Watermark",
    route: "/converter/PDFtools/Pdfwatermark",
    icon: FiFileText,
    category: "pdf",
    acceptedTypes: ["application/pdf", ".pdf"],
    outputType: "pdf",
    maxFiles: 1,
    subtext: "Add custom text or image watermark to PDF",
  },
  "pdf-edit": {
    id: "pdf-edit",
    name: "PDF Edit",
    route: "/converter/PDFtools/Pdfedit",
    icon: FaEdit,
    category: "pdf",
    acceptedTypes: ["application/pdf", ".pdf"],
    outputType: "pdf",
    maxFiles: 1,
    subtext: "Edit and annotate your PDF documents",
  },
  "pdf-rotate": {
    id: "pdf-rotate",
    name: "PDF Rotate",
    route: "/converter/PDFtools/Pdfrotate",
    icon: FaUndo,
    category: "pdf",
    acceptedTypes: ["application/pdf", ".pdf"],
    outputType: "pdf",
    maxFiles: 1,
    subtext: "Rotate pages in your PDF document",
  },
  "pdf-page-no": {
    id: "pdf-page-no",
    name: "PDF Page Numbering",
    route: "/converter/PDFtools/Pdfpageno",
    icon: FaListOl,
    category: "pdf",
    acceptedTypes: ["application/pdf", ".pdf"],
    outputType: "pdf",
    maxFiles: 1,
    subtext: "Add page numbers to your PDF document",
  },
  "pdf-rearrange": {
    id: "pdf-rearrange",
    name: "PDF Page Rearrange",
    route: "/converter/PDFtools/Pdfpagerearange",
    icon: FaExchangeAlt,
    category: "pdf",
    acceptedTypes: ["application/pdf", ".pdf"],
    outputType: "pdf",
    maxFiles: 1,
    subtext: "Reorder or delete pages in your PDF file",
  },
  "pdf-sign": {
    id: "pdf-sign",
    name: "PDF Sign",
    route: "/converter/PDFtools/Pdfsign",
    icon: FaSignature,
    category: "pdf",
    acceptedTypes: ["application/pdf", ".pdf"],
    outputType: "pdf",
    maxFiles: 1,
    subtext: "Sign PDF documents digitally",
  },
  "pdf-deffrence": {
    id: "pdf-deffrence",
    name: "PDF Difference",
    route: "/converter/PDFtools/Pdfdeffrence",
    icon: FaBalanceScale,
    category: "pdf",
    acceptedTypes: ["application/pdf", ".pdf"],
    outputType: "pdf",
    maxFiles: 2,
    subtext: "Compare and find differences between PDF files",
  },
  "word-to-pdf": {
    id: "word-to-pdf",
    name: "Word to PDF",
    route: "/converter/PDFtools/Wordtopdf",
    icon: FaFilePdf,
    category: "pdf",
    acceptedTypes: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document", ".docx", ".doc"],
    outputType: "pdf",
    maxFiles: 1,
    subtext: "Convert DOCX Word documents into PDF",
  },
  "excel-to-pdf": {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    route: "/converter/PDFtools/Excletopdf",
    icon: FaFilePdf,
    category: "pdf",
    acceptedTypes: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ".xlsx", ".xls"],
    outputType: "pdf",
    maxFiles: 1,
    subtext: "Convert Excel spreadsheets to PDF format",
  },

  // ── Image Tools ───────────────────────────────────────────────────
  "image-to-pdf": {
    id: "image-to-pdf",
    name: "Images to PDF",
    route: "/converter/images-to-pdf",
    icon: FaFilePdf,
    category: "pdf",
    acceptedTypes: ["image/jpeg", "image/png", "image/webp", "image/*", ".jpg", ".png", ".webp"],
    outputType: "pdf",
    maxFiles: 100,
    subtext: "Convert your images into a single PDF document",
    badge: "Popular",
  },
  "jpg-to-png": {
    id: "jpg-to-png",
    name: "JPG to PNG",
    route: "/converter/Imagetools/Imagetypeconvert",
    icon: FiRepeat,
    category: "image",
    acceptedTypes: ["image/jpeg", "image/png", "image/webp", "image/*", ".jpg", ".png", ".webp"],
    outputType: "image",
    maxFiles: 50,
    subtext: "Convert image format to PNG, WEBP, or GIF",
  },
  "compress-image": {
    id: "compress-image",
    name: "Compress JPG",
    route: "/converter/Imagetools/Imagecom",
    icon: FiMinimize2,
    category: "image",
    acceptedTypes: ["image/jpeg", "image/png", "image/webp", "image/*", ".jpg", ".png", ".webp"],
    outputType: "image",
    maxFiles: 20,
    subtext: "Reduce JPG image file size without losing quality",
  },
  "image-edit": {
    id: "image-edit",
    name: "Image Edit",
    route: "/converter/Imagetools/Imageedit",
    icon: FiEdit,
    category: "image",
    acceptedTypes: ["image/jpeg", "image/png", "image/webp", "image/*", ".jpg", ".png", ".webp"],
    outputType: "image",
    maxFiles: 1,
    subtext: "Crop, rotate, or adjust image colors",
  },
  "image-extract": {
    id: "image-extract",
    name: "Image Extractor",
    route: "/converter/Imageextract",
    icon: FaFileImage,
    category: "image",
    acceptedTypes: ["application/pdf", ".pdf"],
    outputType: "image",
    maxFiles: 1,
    subtext: "Extract all embedded images from PDF document",
  },
  "ocr-scanner": {
    id: "ocr-scanner",
    name: "OCR Scanner",
    route: "/converter/ocr",
    icon: FaMagic,
    category: "image",
    acceptedTypes: ["image/jpeg", "image/png", "image/webp", "image/*", "application/pdf"],
    outputType: "file",
    maxFiles: 1,
    subtext: "Extract text from image or scanned document",
  },

  // ── Spreadsheet & Data Converters ─────────────────────────────────
  "excel-to-csv": {
    id: "excel-to-csv",
    name: "Excel to CSV",
    route: "/converter/Exceltocsv",
    icon: FaFileCsv,
    category: "spreadsheet",
    acceptedTypes: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ".xlsx", ".xls"],
    outputType: "csv",
    maxFiles: 1,
    subtext: "Convert Excel spreadsheet to CSV file",
  },
  "csv-to-excel": {
    id: "csv-to-excel",
    name: "CSV to Excel",
    route: "/converter/Csvtoexcel",
    icon: FaFileExcel,
    category: "spreadsheet",
    acceptedTypes: ["text/csv", ".csv"],
    outputType: "excel",
    maxFiles: 1,
    subtext: "Convert CSV data file to Excel spreadsheet",
  },

  // ── File Archiving & Security ──────────────────────────────────────
  "files-to-zip": {
    id: "files-to-zip",
    name: "Files to ZIP",
    route: "/converter/files-to-zip",
    icon: FiArchive,
    category: "file",
    acceptedTypes: ["*/*"],
    outputType: "zip",
    maxFiles: 100,
    subtext: "Compress multiple files into a single ZIP archive",
  },
  "decompress-zip": {
    id: "decompress-zip",
    name: "ZIP Decompress",
    route: "/converter/decompress-zip",
    icon: FiArchive,
    category: "file",
    acceptedTypes: ["application/zip", ".zip"],
    outputType: "file",
    maxFiles: 1,
    subtext: "Extract files from a ZIP archive",
  },
  "encrypt-file": {
    id: "encrypt-file",
    name: "Encrypt File",
    route: "/converter/encrypt-file",
    icon: FiLock,
    category: "file",
    acceptedTypes: ["*/*"],
    outputType: "file",
    maxFiles: 1,
    subtext: "Encrypt or decrypt files securely",
  },

  // ── Base64 & Binary Tools ──────────────────────────────────────────
  "image-to-base64": {
    id: "image-to-base64",
    name: "Image to Base64",
    route: "/converter/encoder/image",
    icon: FiCode,
    category: "encoder",
    acceptedTypes: ["image/jpeg", "image/png", "image/webp", "image/*"],
    outputType: "file",
    maxFiles: 1,
    subtext: "Convert images to Base64 string",
  },
  "base64-to-image": {
    id: "base64-to-image",
    name: "Base64 to Image",
    route: "/converter/decoder/image",
    icon: FiImage,
    category: "decoder",
    acceptedTypes: ["text/plain", "*/*"],
    outputType: "image",
    maxFiles: 1,
    subtext: "Decode Base64 string to image file",
  },
  "base64-to-pdf": {
    id: "base64-to-pdf",
    name: "Base64 to PDF",
    route: "/converter/decoder/pdf",
    icon: FaFilePdf,
    category: "decoder",
    acceptedTypes: ["text/plain", "*/*"],
    outputType: "pdf",
    maxFiles: 1,
    subtext: "Decode Base64 string to PDF document",
  },
  "ascii-to-base64": {
    id: "ascii-to-base64",
    name: "ASCII to Base64",
    route: "/converter/encoder/ascii",
    icon: FiCode,
    category: "encoder",
    acceptedTypes: ["*/*"],
    outputType: "file",
    maxFiles: 1,
    subtext: "Encode ASCII text to Base64",
  },
  "file-to-base64": {
    id: "file-to-base64",
    name: "File to Base64",
    route: "/converter/encoder/file",
    icon: FiCode,
    category: "encoder",
    acceptedTypes: ["*/*"],
    outputType: "file",
    maxFiles: 1,
    subtext: "Convert any file to Base64 representation",
  },
};

// Aliases for slug compatibility
TOOLS_REGISTRY["ocr"] = TOOLS_REGISTRY["ocr-scanner"];

/**
 * Fallback static map if dynamic matching returns empty.
 */
export const relatedToolsMap: Record<string, string[]> = {
  "pdf-to-jpg": ["compress-image", "image-to-pdf", "jpg-to-png", "files-to-zip"],
  "image-to-pdf": ["pdf-to-word", "pdf-merge", "pdf-split", "pdf-watermark"],
  "jpg-to-png": ["compress-image", "image-to-pdf", "image-edit"],
  "compress-image": ["jpg-to-png", "image-to-pdf", "files-to-zip"],
  "pdf-to-word": ["pdf-to-jpg", "pdf-edit", "pdf-merge"],
  "pdf-merge": ["pdf-split", "pdf-watermark", "pdf-to-jpg"],
  "pdf-split": ["pdf-merge", "pdf-to-jpg", "pdf-to-word"],
  "encrypt-file": ["files-to-zip", "decompress-zip", "pdf-to-jpg", "compress-image"],
};

/**
 * Contextual subtexts displayed per output type
 */
export const outputContextSubtexts: Record<string, string> = {
  image: "Take your converted JPG / Image files further with these tools",
  pdf: "Perform additional actions on your generated PDF document",
  docx: "Continue editing or formatting your converted Word document",
  csv: "Convert, format, or process your CSV spreadsheet data",
  excel: "Convert, format, or export your Excel spreadsheet data",
  zip: "Decompress, encrypt, or manage your ZIP archive files",
  file: "Continue your workflow with these related tools",
  default: "Continue your workflow with these related tools",
};

export const toolContextSubtexts = outputContextSubtexts;

/**
 * Detects output file format from converted file objects or defaults to tool's defined outputType
 */
export function detectOutputType(convertedFiles?: any[], defaultOutputType?: OutputFormat): OutputFormat {
  if (convertedFiles && convertedFiles.length > 0) {
    const first = convertedFiles[0];
    const type = (first.type || first.blob?.type || first.file?.type || "").toLowerCase();
    const name = (first.name || first.fileName || first.file?.name || "").toLowerCase();

    if (type.includes("pdf") || name.endsWith(".pdf")) {
      return "pdf";
    }
    if (
      type.includes("image") ||
      name.endsWith(".jpg") ||
      name.endsWith(".jpeg") ||
      name.endsWith(".png") ||
      name.endsWith(".webp") ||
      name.endsWith(".gif")
    ) {
      return "image";
    }
    if (type.includes("csv") || name.endsWith(".csv")) {
      return "csv";
    }
    if (type.includes("spreadsheet") || type.includes("excel") || name.endsWith(".xlsx") || name.endsWith(".xls")) {
      return "excel";
    }
    if (type.includes("word") || type.includes("officedocument.word") || name.endsWith(".docx") || name.endsWith(".doc")) {
      return "docx";
    }
    if (type.includes("zip") || name.endsWith(".zip")) {
      return "zip";
    }
  }

  return defaultOutputType || "file";
}

/**
 * Helper to check if an output format is accepted by a destination tool
 */
export function isFormatAcceptedByTool(outputFormat: OutputFormat, tool: ToolMeta): boolean {
  if (!tool.acceptedTypes || tool.acceptedTypes.includes("*/*")) return true;

  if (outputFormat === "image") {
    return tool.acceptedTypes.some(
      (t) => t.includes("image") || t.endsWith(".jpg") || t.endsWith(".png") || t.endsWith(".webp")
    );
  }
  if (outputFormat === "pdf") {
    return tool.acceptedTypes.some((t) => t.includes("pdf") || t.endsWith(".pdf"));
  }
  if (outputFormat === "csv") {
    return tool.acceptedTypes.some((t) => t.includes("csv") || t.endsWith(".csv"));
  }
  if (outputFormat === "excel") {
    return tool.acceptedTypes.some((t) => t.includes("excel") || t.includes("spreadsheet") || t.endsWith(".xlsx") || t.endsWith(".xls"));
  }
  if (outputFormat === "docx") {
    return tool.acceptedTypes.some((t) => t.includes("word") || t.endsWith(".docx") || t.endsWith(".doc"));
  }
  if (outputFormat === "zip") {
    return tool.acceptedTypes.some((t) => t.includes("zip") || t.endsWith(".zip"));
  }

  return false;
}

/**
 * Dynamically retrieves tools that accept the specified output format as their input.
 */
export function getDynamicRelatedTools(
  currentToolId: string,
  outputType?: OutputFormat,
  maxCount: number = 4,
  convertedFiles?: any[]
): ToolMeta[] {
  const currentTool = TOOLS_REGISTRY[currentToolId];
  const detectedFormat = detectOutputType(convertedFiles, outputType || currentTool?.outputType);

  const matchedTools: ToolMeta[] = [];

  for (const [id, tool] of Object.entries(TOOLS_REGISTRY)) {
    if (id === currentToolId) continue;

    if (isFormatAcceptedByTool(detectedFormat, tool)) {
      matchedTools.push(tool);
    }
  }

  // Ensure "files-to-zip" is included as an option if space remains
  if (matchedTools.length < maxCount && TOOLS_REGISTRY["files-to-zip"] && currentToolId !== "files-to-zip") {
    if (!matchedTools.some((t) => t.id === "files-to-zip")) {
      matchedTools.push(TOOLS_REGISTRY["files-to-zip"]);
    }
  }

  // Fallback to static mapping if no tools matched
  if (matchedTools.length === 0 && relatedToolsMap[currentToolId]) {
    for (const fallbackId of relatedToolsMap[currentToolId]) {
      if (TOOLS_REGISTRY[fallbackId]) {
        matchedTools.push(TOOLS_REGISTRY[fallbackId]);
      }
    }
  }

  return matchedTools.slice(0, maxCount);
}

/**
 * Helper to retrieve related ToolMeta objects for a given tool slug.
 */
export function getRelatedTools(currentToolSlug: string, maxCount: number = 4, convertedFiles?: any[]): ToolMeta[] {
  return getDynamicRelatedTools(currentToolSlug, undefined, maxCount, convertedFiles);
}

/**
 * Helper to check if a specific file MIME type is accepted by a destination tool ID
 */
export function isFileTypeAcceptedByTool(fileType: string, toolId: string): boolean {
  const tool = TOOLS_REGISTRY[toolId];
  if (!tool) return true;

  const accepted = tool.acceptedTypes;
  if (!accepted || accepted.includes("*/*")) return true;

  const mime = fileType.toLowerCase();
  for (const pattern of accepted) {
    if (pattern === mime) return true;
    if (pattern.endsWith("/*")) {
      const mainType = pattern.split("/")[0];
      if (mime.startsWith(`${mainType}/`)) return true;
    }
    if (pattern.startsWith(".") && mime.includes(pattern.replace(".", ""))) return true;
  }

  return false;
}
